language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - '7.0'
  - hhvm
branches:
  only:
    - develop
    - master
before_script:
    - composer -n --no-ansi install --dev --prefer-source
    - cp phpunit.xml.travis phpunit.xml
matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'
sudo: false
